# Kestrel-original recipe (status: independent, not a Fedora dist-git import).
# Upstream: https://github.com/jeremy-rifkin/cpptrace (tag v1.0.4).
# Source0 MUST match pigeon/config/upstream-sources.json (verified by
# source_pipeline.py before any build).

Name:           cpptrace
Version:        1.0.4
Release:        1.hum1.pigeon
Summary:        C++ stack trace library
License:        MIT
URL:            https://github.com/jeremy-rifkin/cpptrace
Source0:        https://github.com/jeremy-rifkin/cpptrace/archive/refs/tags/v%{version}.tar.gz

BuildRequires:  gcc-c++
BuildRequires:  cmake
BuildRequires:  ninja-build
BuildRequires:  pkgconfig
BuildRequires:  elfutils-libelf-devel
BuildRequires:  libunwind-devel
BuildRequires:  libzstd-devel

%description
cpptrace is a C++ library for generating stack traces. It provides a simple
API for capturing and formatting stack traces, with support for demangling
symbol names and inline assembly.

%prep
%autosetup -n cpptrace-%{version} -p1

%build
%cmake -GNinja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCPPTRACE_BUILD_SHARED=ON \
  -DCPPTRACE_USE_EXTERNAL_ZSTD=ON
%cmake_build

%install
%cmake_install
# Fix cpptrace-config.cmake to use CONFIG mode for zstd (avoid Findzstd.cmake)
CONFIG_FILE=%{buildroot}%{_libdir}/cmake/cpptrace/cpptrace-config.cmake
# The file was generated by CMake with @...@ placeholders already expanded.
# Insert find_dependency(zstd CONFIG REQUIRED) after the @PACKAGE_INIT@ line
sed -i '/^@PACKAGE_INIT@/a find_dependency(zstd CONFIG REQUIRED)' "$CONFIG_FILE"
# Remove the module-path/Findzstd logic that follows
sed -i '/set(CMAKE_MODULE_PATH_OLD/,/unset(CMAKE_MODULE_PATH_OLD)/d' "$CONFIG_FILE"
sed -i '/set(CMAKE_MODULE_PATH "\${CMAKE_MODULE_PATH};/d' "$CONFIG_FILE"
sed -i '/find_dependency(zstd)/d' "$CONFIG_FILE"
sed -i '/set(CMAKE_MODULE_PATH "\${CMAKE_MODULE_PATH_OLD}")/d' "$CONFIG_FILE"
sed -i '/unset(CMAKE_MODULE_PATH_OLD)/d' "$CONFIG_FILE"
# Remove the installed Findzstd.cmake
rm -f %{buildroot}%{_libdir}/cmake/cpptrace/Findzstd.cmake

%files
%license LICENSE
%{_libdir}/libcpptrace.so.*
%{_includedir}/cpptrace/
%exclude %{_includedir}/ctrace/
%exclude %{_includedir}/dwarf.h
%exclude %{_includedir}/libdwarf.h
%exclude %{_libdir}/cmake/libdwarf/
%exclude %{_libdir}/cmake/zstd/
%exclude %{_libdir}/libdwarf.a
%exclude %{_libdir}/pkgconfig/libdwarf.pc

%package devel
Summary:        Development files for %{name}
Requires:       %{name}%{?_isa} = %{version}-%{release}

%description devel
Development files for cpptrace, including headers and CMake configuration.

%files devel
%license LICENSE
%{_libdir}/libcpptrace.so
%{_libdir}/cmake/cpptrace/
%{_includedir}/cpptrace/
%exclude %{_includedir}/ctrace/
%exclude %{_includedir}/dwarf.h
%exclude %{_includedir}/libdwarf.h
%exclude %{_libdir}/cmake/libdwarf/
%exclude %{_libdir}/cmake/zstd/
%exclude %{_libdir}/libdwarf.a
%exclude %{_libdir}/pkgconfig/libdwarf.pc

%changelog
* Fri Sep 18 2026 Kestrel <kestrel@localhost> - 1.0.4-1.hum1.pigeon
- Initial Kestrel package for cpptrace