#!/usr/bin/env python3
"""Deterministic YAML rendering for pigeon/.packit.yaml.

Mirrors utah-packages/tools/render_packit_config.py: the file is generated
from the inventory so it can never drift from the recipe dirs on disk.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from package_inventory import inventory, source_locks

HEADER = """# Root-level Packit monorepo config for the Pigeon package factory.
# Generated by pigeon/tools/render_packit_config.py -- do not edit manually.
# Mirrors utah-packages/.packit.yaml: create-archive action stages the
# factory's already-verified Source0 archive (packit_source0.py) instead of
# letting Packit fetch upstream itself.
actions:
  create-archive:
    - bash -c 'python3 "$(git rev-parse --show-toplevel)/pigeon/tools/packit_source0.py"'
packages:
"""


def render(root: Path) -> str:
    records = inventory(root)
    lock_map = source_locks(root)

    lines = [HEADER.rstrip("\n")]
    for record in sorted(records, key=lambda r: r.name):
        entry = lock_map.get(record.name, {})
        source_name = entry.get("upstream_package_name", record.name)
        spec_filename = record.spec.name
        lines.append(f"  {record.name}:")
        lines.append(f"    specfile_path: pigeon/packages/{record.name}/{spec_filename}")
        lines.append(f"    upstream_package_name: {source_name}")
        lines.append(f"    downstream_package_name: {source_name}")
        lines.append("    paths:")
        lines.append(f"      - pigeon/packages/{record.name}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true",
                        help="write to pigeon/.packit.yaml")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    rendered = render(root)
    if args.write:
        (root / "pigeon" / ".packit.yaml").write_text(rendered)
    else:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())